### ISSUE TITLE
Desktop mode avatar view is glitchy

### ISSUE THREAD

**Issue by troyBORG** [Frozenreflex/Thundagun#77] opened 2024-11-25 19:24 UTC
https://github.com/user-attachments/assets/9b5ca87e-8046-4173-8500-0370ec1fa5a4

**Comment by wisemagick1** [comment] 2024-11-25 19:52
If I understand right this is the same as #4 . If not, this issue also does occur in VR

**Comment by troyBORG** [comment] 2024-11-25 20:26
I didn't get a chance to test it in VR yet.

**Comment by DoubleStyx** [comment] 2024-11-26 01:34
Duplicate of #4

**Closed by DoubleStyx** 2024-11-26 01:34 UTC

**Comment by troyBORG** [comment] 2024-11-30 01:15
Yep, I did test it in VR and I am like bobbing up and down and disappearing as I'm moving around.
