### ISSUE TITLE
Unity crash on launch.

### ISSUE THREAD

**Issue by AntonBoch1244** [Frozenreflex/Thundagun#93] opened 2024-12-14 12:39 UTC
Mod version: 1.2.0
Mod loader: Resonite Mod Loader
Mod loader version: 3.0.0
Resonite version: Beta 2024.12.10.482

Expected:
I started the application and it just works.

Actual:
After opening the local world, I've got unity crash.

On mod version 1.1.1 expected behavior, but Windows cursor is shown in the application.

**Comment by AntonBoch1244** [comment] 2024-12-14 12:46
HW:
- CPU: AMD Ryzen 7 5700G
- iGPU: AMD Radeon Graphics (Programmable disabled)
- dGPU: AMD Radeon RX 5700 XT

**Comment by AntonBoch1244** [comment] 2024-12-15 01:50
I've bisected good and bad commits for this modification.

A good first commit before the issue appeared in 4850c1f46838a80a5876a212d1067d411523b2fc.
A bad first commit is 0b1aa0bc1a98ade084fb7abf6dcd1f980ade006e.
A bad last commit is dd47980d896a9a5bd8a2750154d5701d3478c9b4.
A good first after the issue, a fix introduced in 72bff92dfa1f3ca59703ce7c62ba54f532cfaf04 commit.
A good first after the issue, a fix in main development branch introduced in f02e964b7d4a1a6580ad968e7aa93ff694947a43 commit.
Considering retag version 1.2.0 to 416a23f895b6e111601f0064491f194d490f618a commit.

**Comment by Nytra** [comment] 2024-12-15 08:08
Does using the latest master not resolve this issue?

**Comment by tgrafk12** [comment] 2024-12-15 22:39
Same, Gets a crash barely loading the main screen.
[system_specs_2024-11-09_20-58-03.txt](https://github.com/user-attachments/files/18142421/system_specs_2024-11-09_20-58-03.txt)

Specs page is listed as a TXT file

anyway, I duno what else to log besides that it loads main files, and then hard crashes after 30 seconds.

**Comment by AntonBoch1244** [comment] 2024-12-15 23:08
> Does using the latest master not resolve this issue?

After https://github.com/Frozenreflex/Thundagun/commit/72bff92dfa1f3ca59703ce7c62ba54f532cfaf04, https://github.com/Frozenreflex/Thundagun/commit/f02e964b7d4a1a6580ad968e7aa93ff694947a43 issue fixed. So master have fix built-in.

**Comment by BlueberryWolf** [comment] 2024-12-22 08:36
The crashes seem to be caused by Resonite refactoring Particle Systems, and I have made a hotfix pull request to prevent the crashes by linking to the legacy particle systems instead. #94

**Comment by Nytra** [comment] 2024-12-22 22:00
Fixed in https://github.com/Frozenreflex/Thundagun/releases/tag/1.2.1 thanks

**Closed by Nytra** 2024-12-22 22:00 UTC
