### ISSUE TITLE
Entering 'DeSync' Mode causes UIX to stop working

### ISSUE THREAD

**Issue by NepuShiro** [Frozenreflex/Thundagun#35] opened 2024-11-05 14:18 UTC
When forcing Desync Mode or having it automatically switch it causes any active UIX in use to break. might be related to #32 

In the Mod Settings setting the threshold for Desync Mode to 0 causes the mod settings to become unresponsive, duplicating the Page fixes it, but it's inoperable due to references being broken.

I've also encountered this in the wild with Inspectors suddenly locking up and requiring a duplicate.

**Comment by DoubleStyx** [comment] 2024-11-05 18:04
Hm, I'm not able to reproduce this on desktop currently. I'll see if it's more of an issue in VR later.

**Comment by DoubleStyx** [comment] 2024-11-05 18:12
Does this happen on main or the #31 branch? #31 has predicates for the mod settings to prevent invalid values for certain settings.

**Comment by DoubleStyx** [comment] 2024-11-05 20:23
I'm still getting this issue. We need to look into this more. I'll see if it's a specific mode that's causing problems. 

I believe the issue is that the UI might expect certain RenderTasks to be completed, but only processing part of a batch might cause it to enter an invalid state.

I hope that we can address this, otherwise we won't be able to support desync behavior. There would be no way to cancel a batch early. You could try to estimate based on the number of tasks, but this isn't very reliable.

It might be worth validating the logic for how the queuing and batching is handled to see if it's introducing potential synchronization issues.

**Comment by DoubleStyx** [comment] 2024-11-06 02:36
Might be addressed by #37?

**Comment by NepuShiro** [comment] 2024-11-06 03:23
> Might be addressed by #37?

I just built #37 and ran it, everything seemed fine, until not even a couple of minutes in the Notifcations UIX/Slots got stuck on screen and didn't update, and any Userspace inspector I would spawn would work for about 5 seconds before completely locking up. after a restart everything seems to be running fine now?

**Comment by DoubleStyx** [comment] 2024-11-06 04:56
@NepuShiro Yeah, I was worried about this still being an issue. I'm not sure there's any way to fix it actually. It might be related to not batching the changes, though. That's one thing you can try. Another might be to enforce a more unidirectional approach, where Resonite updates to Unity updates is 1:N, which ensures Unity has processed all changes before FrooxEngine completes another cycle. This would definitely work, but it means there's no way for FrooxEngine to keep doing work in the background. Though maybe these issues suggest that that's a bad idea overall.

**Comment by DoubleStyx** [comment] 2024-11-06 07:36
Check out #42.

**Comment by NepuShiro** [comment] 2024-11-06 10:24
@DoubleStyx That PR doesn't seem to fix it as I'm still having my inspectors and the Mic Status locking up and has brought on some terrible jittery effects. Like everything is a frame behind and it's trying to catch up

**Comment by DoubleStyx** [comment] 2024-11-07 00:31
Try the latest release. It should prevent FrooxEngine from updating if Unity hasn't processed the changes, which should hopefully prevent UI from breaking.

**Comment by NepuShiro** [comment] 2024-11-08 06:20
It seems to be a bit better now; it still tends to happen every now and then but not as often as before.

**Comment by Nytra** [comment] 2024-11-12 22:37
From my testing, UIX will stop working at random times when render incomplete updates is enabled. I think this may be because FrooxEngine waits until the end of the update to finalize UIX. We could maybe patch this to happen earlier which may fix the UIX breakage.

**Comment by DoubleStyx** [comment] 2024-11-20 08:04
I'm not really sure what this issue is targeting at this point. The mod setting in question doesn't exactly exist anymore. If there are other bugs related to the mod, please make a separate issue.

**Closed by DoubleStyx** 2024-11-20 08:04 UTC
Labels: bug
